# Generated by Django 5.2.3 on 2025-06-22 09:34

import Organizer.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='*Allowed names contain letters, digits, spaces, and hyphens.', max_length=110, unique=True, validators=[django.core.validators.MinLengthValidator(2), Organizer.validators.AlphaNumericHyphenSpaceValidator()])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[Organizer.validators.phone_validator])),
                ('secret_key', models.CharField(help_text='*Pick a combination of 4 unique digits.', max_length=4, validators=[Organizer.validators.SecretKeyValidator()])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
